### ISSUE TITLE
Import error on python 3.4

### ISSUE THREAD

**Issue by jacobmontiel** [hammerlab/fancyimpute#13]
I am getting the following error triggered by:
import fancyimpute

------------------------------------------------------------------------------
Using Theano backend.
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/theano/gof/lazylinker_c.py", line 74, in <module>
    raise ImportError()
ImportError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/theano/gof/lazylinker_c.py", line 91, in <module>
    raise ImportError()
ImportError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/theano/gof/vm.py", line 638, in <module>
    from . import lazylinker_c
  File "/usr/local/lib/python3.4/site-packages/theano/gof/lazylinker_c.py", line 126, in <module>
    preargs=args)
  File "/usr/local/lib/python3.4/site-packages/theano/gof/cmodule.py", line 2139, in compile_str
    with open(cppfilename, 'w') as cppfile:
PermissionError: [Errno 13] Permission denied: '/home/jacob/.theano/compiledir_Linux-4.4--generic-x86_64-with-debian-stretch-sid-x86_64-3.4.1-64/lazylinker_ext/mod.cpp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "runImputeData.py", line 15, in <module>
    from fancyimpute import KNN
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/usr/local/lib/python3.4/site-packages/fancyimpute-0.0.16-py3.4.egg/fancyimpute/__init__.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/usr/local/lib/python3.4/site-packages/fancyimpute-0.0.16-py3.4.egg/fancyimpute/auto_encoder.py", line 19, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/usr/local/lib/python3.4/site-packages/fancyimpute-0.0.16-py3.4.egg/fancyimpute/neuralnet_helpers.py", line 16, in <module>
  File "/usr/local/lib/python3.4/site-packages/Keras-1.0.3-py3.4.egg/keras/__init__.py", line 2, in <module>
    from . import backend
  File "/usr/local/lib/python3.4/site-packages/Keras-1.0.3-py3.4.egg/keras/backend/__init__.py", line 51, in <module>
    from .theano_backend import *
  File "/usr/local/lib/python3.4/site-packages/Keras-1.0.3-py3.4.egg/keras/backend/theano_backend.py", line 1, in <module>
    import theano
  File "/usr/local/lib/python3.4/site-packages/theano/__init__.py", line 63, in <module>
    from theano.compile import (
  File "/usr/local/lib/python3.4/site-packages/theano/compile/__init__.py", line 9, in <module>
    from theano.compile.function_module import *
  File "/usr/local/lib/python3.4/site-packages/theano/compile/function_module.py", line 22, in <module>
    import theano.compile.mode
  File "/usr/local/lib/python3.4/site-packages/theano/compile/mode.py", line 12, in <module>
    import theano.gof.vm
  File "/usr/local/lib/python3.4/site-packages/theano/gof/vm.py", line 653, in <module>
    if x.fullname == 'linker'][0].default.startswith('cvm'), e
AssertionError: [Errno 13] Permission denied: '/home/jacob/.theano/compiledir_Linux-4.4--generic-x86_64-with-debian-stretch-sid-x86_64-3.4.1-64/lazylinker_ext/mod.cpp'
------------------------------------------------------------------------------

I can bypass it using sudo but then I get this:

------------------------------------------------------------------------------
Exception: Compilation failed (return status=1): /usr/bin/ld: /usr/local/lib/libpython3.4m.a(abstract.o): relocation R_X86_64_32S against `_Py_NotImplementedStruct' can not be used when making a shared object; recompile with -fPIC. /usr/local/lib/libpython3.4m.a: error adding symbols: Bad value. collect2: error: ld returned 1 exit status.
------------------------------------------------------------------------------

Any suggestion is welcomed.

**Comment by iskandr** [comment]
Are you able to use Theano or Keras separate from this library? This looks like a problem with your system's ability to call a compiler from within Python.
